### ISSUE TITLE
Editor timing panel glitchiness

### ISSUE THREAD

**Issue by Luminiscental** [NelloKudo/osu-winello#86] opened 2024-08-16 21:20 UTC
With a fresh install of winello and `WINE_DISABLE_GLCHILD_HACK=1`, I get that the timing panel in the editor has weird visual artifacts (screenshot below) and also half the time the buttons are uninteractable (maybe uninteractable until re-selecting a green line on the right? haven't tested much).

FWIW I'm on arch with i3wm, which I'm aware can cause some jankiness with popup windows like this, but re-switching focus, resizing e.t.c. doesn't make any difference for me here.

![Screenshot_2024-08-16_22-11](https://github.com/user-attachments/assets/f06b35ea-8d9c-4f1a-91c0-e82808e8b842)

**Comment by VelamyGH** [comment] 2024-08-19 18:44
same issues on my end as well, able to reproduce on arch (specifically on KDE and x11)

i've also had a lot more editor issues than this, but ill show everything on my end here;

- File, Edit, and View buttons not showing: 
![image](https://github.com/user-attachments/assets/8f8e3dae-11d3-40c3-9b2d-5f7d0193cd70)

- Timing panel glitchiness (this appears to *mostly* fix itself after tabbing out and back in? not 100% sure on this): 
![image](https://github.com/user-attachments/assets/89ea4058-fd25-4263-969d-54d8a91ded86)

- Stat change numbers not showing on the adjustments sliders (makes it just completely unable to tell what number i'm setting, especially for decimal values):
![image](https://github.com/user-attachments/assets/f4231c77-effa-41d5-9040-94e191355939)
![image](https://github.com/user-attachments/assets/2da52f27-aebc-403d-a8d6-1ff6d9643b70)

**Comment by NelloKudo** [comment] 2024-08-19 18:50
> same issues on my end as well, able to reproduce on arch (specifically on KDE and x11)
> 
> i've also had a lot more editor issues than this, but ill show everything on my end here;
> 
> * File, Edit, and View buttons not showing:
>   ![image](https://private-user-images.githubusercontent.com/48131627/359208830-8f8e3dae-11d3-40c3-9b2d-5f7d0193cd70.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQwOTM0NzksIm5iZiI6MTcyNDA5MzE3OSwicGF0aCI6Ii80ODEzMTYyNy8zNTkyMDg4MzAtOGY4ZTNkYWUtMTFkMy00MGMzLTliMmQtNWY3ZDAxOTNjZDcwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE5VDE4NDYxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ3ZGZkNDYzYmI2MWM1YjcyYjVhZmE2ODg3YjBmNDhjYTMxZTJiY2E4MmQ0YjQzMTNhNmI2ZTU3NGJkMmJmNzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lzBh0kMIExhteNcYzhcZ-HbANZaLEBZ02XpTzNJgJ0U)
> * Timing panel glitchiness (this appears to _mostly_ fix itself after tabbing out and back in? not 100% sure on this):
>   ![image](https://private-user-images.githubusercontent.com/48131627/359209243-89ea4058-fd25-4263-969d-54d8a91ded86.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQwOTM0NzksIm5iZiI6MTcyNDA5MzE3OSwicGF0aCI6Ii80ODEzMTYyNy8zNTkyMDkyNDMtODllYTQwNTgtZmQyNS00MjYzLTk2OWQtNTRkOGE5MWRlZDg2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE5VDE4NDYxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgyN2ZhYTkyMWRhMjFiMTkyMGI1NWYxNTBhYzlkYjU0N2QwZjgyODJhMzViYmQ3Njc4MWE5N2ZmMDc5ZTFiNWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yGQqHtLW9tMRUyXALI4BjCwiYZwSO6bkC35fIyOuQsY)
> * Stat change numbers not showing on the adjustments sliders (makes it just completely unable to tell what number i'm setting, especially for decimal values):
>   ![image](https://private-user-images.githubusercontent.com/48131627/359209429-f4231c77-effa-41d5-9040-94e191355939.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQwOTM0NzksIm5iZiI6MTcyNDA5MzE3OSwicGF0aCI6Ii80ODEzMTYyNy8zNTkyMDk0MjktZjQyMzFjNzctZWZmYS00MWQ1LTkwNDAtOTRlMTkxMzU1OTM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE5VDE4NDYxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg3YWQ0N2ExOTAzZDAwODcxZTlkOWNjNDc1OThmMTNiMDA5ZTVmODg4MmUxYWRmOTBkOTkwYWIwNGM5YzdiMjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BS5FBUI9miIhxroX6yeoZmQao43WFsZimNJhRM26x98)
>   ![image](https://private-user-images.githubusercontent.com/48131627/359209452-2da52f27-aebc-403d-a8d6-1ff6d9643b70.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQwOTM0NzksIm5iZiI6MTcyNDA5MzE3OSwicGF0aCI6Ii80ODEzMTYyNy8zNTkyMDk0NTItMmRhNTJmMjctYWViYy00MDNkLWE4ZDYtMWZmNmQ5NjQzYjcwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE5VDE4NDYxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY4MDgzODUxNTYzNjQ3Nzk2NzA0YTQ0ZDRkZDUzYjQxYzg4M2NlYWMwNWIwZjNmYWI2NmZlODVlNjkzMjQwMWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yrQR1NOkYcgDtzhkimU5UeV4FRxagSvUs40lValA89w)

Some of those issues you mentioned are fixed by setting `WINE_DISABLE_GLCHILD_HACK=1` in ~/.local/bin/osu-wine

The timing panel issues is probably due to some change in Wine we haven’t investigated yet, we’ll get there eventually but trying out the other Wine releases in [WineBuilder](https://github.com/NelloKudo/WineBuilder/releases) might fix it.

**Comment by Luminiscental** [comment] 2024-08-19 18:54
To be clear the stat change tooltips not appearing properly also isn't fixed by `WINE_DISABLE_GLCHILD_HACK=1`

**Comment by Luminiscental** [comment] 2024-08-19 19:45
Notes:
- The visual artifacts are triggered by moving the cursor over the buttons
- When a button gets rendered in multiple locations only the most recent one is interactable
- Among the [WineBuilder](https://github.com/NelloKudo/WineBuilder/releases) releases, it seems this issue first appears in [wine-osu-9.11-staging](https://github.com/NelloKudo/WineBuilder/releases/tag/wine-osu-staging-9.11):

I tested:
- [wine-osu-wow64-9.14-staging](https://github.com/NelloKudo/WineBuilder/releases/tag/wine-osu-wow64-staging-9.14), [wine-osu-9.14-staging](https://github.com/NelloKudo/WineBuilder/releases/tag/wine-osu-staging-9.14), [wine-osu-9.11-staging](https://github.com/NelloKudo/WineBuilder/releases/tag/wine-osu-staging-9.11) => issue present
- [wine-osu-protonGE-9-4](https://github.com/NelloKudo/WineBuilder/releases/tag/wine-osu-protonGE-9-4), [wine-osu-protonGE-9-2](https://github.com/NelloKudo/WineBuilder/releases/tag/wine-osu-protonGE-9-2), [wine-osu-tkg 9.0-rc1-v2](https://github.com/NelloKudo/WineBuilder/releases/tag/wine-osu-tkg-9.0-rc1-v2), [wine-osu-stable 7.16](https://github.com/NelloKudo/WineBuilder/releases/tag/wine-osu-stable-7.16) => issue not present

Also the scroll reset issue when clicking on the timing point list isn't present in [wine-osu-stable 7.16](https://github.com/NelloKudo/WineBuilder/releases/tag/wine-osu-stable-7.16), but is present from [wine-osu-tkg 9.0-rc1-v2](https://github.com/NelloKudo/WineBuilder/releases/tag/wine-osu-tkg-9.0-rc1-v2) onwards, so I guess some regression happened there

**Comment by Luminiscental** [comment] 2024-08-21 09:29
> Let me know if you still experience this problem with this build (still with `WINE_DISABLE_GLCHILD_HACK=1`):
> 
> https://github.com/whrvt/WineBuilder/releases/tag/v9.15-editor-testing
> 
> edit: accidentally uploaded the wrong binary

This build fixes all the issues I encountered!

**Comment by NelloKudo** [comment] 2024-08-21 10:49
spectator cooking as usual 🍷

releasing a new build as soon as I have a working setup!

**Comment by Luminiscental** [comment] 2024-08-22 22:07
Ok actually there is one issue with that 9.15 build; the rotate dialogue no longer opens with the angle selected for replacement, so instead of just `ctrl+shift+R, 5` to rotate by 5 degrees I have to do `ctrl+shift+r, select textbox, 5`

**Comment by Luminiscental** [comment] 2024-08-23 08:23
> > the rotate dialogue no longer opens with the angle selected for replacement
> 
> I never would have even realized that was a problem, because I don't have any muscle memory in the editor. If this build fixes the issue for you (it works for me on a clean prefix), we should be able to make a stable release in the next few days. https://github.com/whrvt/WineBuilder/releases/tag/v9.15-editor-testing-2

This fixes the rotate dialogue for me!

**Comment by NelloKudo** [comment] 2024-08-23 08:25
Closing this once I release the build then! Thanks everyone for the help, debugging editor is nothing but pain 🥲

*im hopefully releasing soon, almost done with vacation!*

**Closed** 2024-08-24 10:01 UTC
