### ISSUE TITLE
osu! crash when exiting a song or passing a map

### ISSUE THREAD

**Issue by risexd1** [NelloKudo/osu-winello#65] opened 2024-03-17 19:46 UTC
im using zorin os and sometimes the game just freezes with a black screen when i exit a song or pass a map
it says osu!.exe is not responding and i can force quit the game
this issue didnt happen to me on other distros

**Comment by Jeydin21** [comment] 2024-04-07 04:49
This issue is happening to me on Ubuntu 23.10 as well

**Comment by NelloKudo** [comment] 2024-04-07 19:22
Can you provide any logs?

**Comment by Jeydin21** [comment] 2024-04-08 03:03
```sh
0024:fixme:rawinput:NtUserRegisterRawInputDevices Unhandled flags 0x200 for device 0.
0318:fixme:thread:NtQueryInformationThread ThreadIsIoPending info class not supported yet
030c:fixme:thread:NtQueryInformationThread ThreadIsIoPending info class not supported yet
030c:fixme:thread:NtQueryInformationThread ThreadIsIoPending info class not supported yet
0024:fixme:crypt:SystemFunction041 (08EA8784, 10, 0): stub [RtlDecryptMemory]
0024:fixme:crypt:SystemFunction040 (08EA8784, 10, 0): stub [RtlEncryptMemory]
031c:fixme:thread:NtQueryInformationThread ThreadIsIoPending info class not supported yet
0370:fixme:thread:NtQueryInformationThread ThreadIsIoPending info class not supported yet
0024:fixme:crypt:SystemFunction041 (08EA8784, 10, 0): stub [RtlDecryptMemory]
0024:fixme:crypt:SystemFunction040 (08EA8784, 10, 0): stub [RtlEncryptMemory]
036c:fixme:thread:NtQueryInformationThread ThreadIsIoPending info class not supported yet
0024:fixme:crypt:SystemFunction041 (08EA8784, 10, 0): stub [RtlDecryptMemory]
0024:fixme:crypt:SystemFunction040 (08EA8784, 10, 0): stub [RtlEncryptMemory]
0398:err:sync:RtlpWaitForCriticalSection section 0035E308 (null) wait timed out in thread 0398, blocked by 0024, retrying (60 sec)
/home/jeydin/.local/bin/osu-wine: line 66: 367755 Killed                  $LAUNCH_ARGS wine "$OSUPATH/osu!.exe"
```
I'm not sure what the top lines mean but when I finish a map it freezes the screen and then it says the Osu isn't responding. This only happens occasionally though, it's kind of random

**Comment by Jeydin21** [comment] 2024-04-08 03:16
https://github.com/NelloKudo/osu-winello/assets/62669147/144aac3b-5f24-4504-a468-cde0753a368c
Don't mind my accuracy :sob:

**Comment by NelloKudo** [comment] 2024-04-08 11:32
> 2024-04-07.22-12-55.mp4 
> 
> Don't mind my accuracy 😭 It was so bad I crashed Osu 😭 😭 😭

Kinda unrelated to the issue, but are you sure your drivers are installed properly? 17ms is waaay too much :/ 
Check the drivers page in the repo and run the commands again or try changing kernel!!

**Comment by NelloKudo** [comment] 2024-04-08 11:35
Since logs seem to fail in `sync`, I wonder if fsync is the culprit here…
Run `osu-wine --update` to make sure you’re on the latest Wine version and, if that doesn’t help, follow [this](https://github.com/NelloKudo/osu-winello/wiki/Game-stutters--%E2%80%90--Random-crashes#random-crashes--freezes) (the fsync part!!)

**Comment by risexd1** [comment] 2024-04-08 11:37
i tried disabling fsync and it didnt work

**Comment by Jeydin21** [comment] 2024-04-09 03:35
Same here

**Comment by NelloKudo** [comment] 2024-04-09 14:49
Then can you try editing `~/.local/bin/osu-wine` and commenting out (or deleting) `WINE_BLOCK_GET_VERSION=1`?

**Comment by LixxRarin** [comment] 2024-06-04 21:34
It happens to me too, in this script and in lutris, I have no solution so far ): (I also use Zorin OS)

**Comment by dceit** [comment] 2024-06-26 04:59
Hello farmers, I come here with a possible fix which worked on my fresh installation of Debian using i3wm.

Before I was showing similar issues, the game would freeze up whenever submitting scores, exiting a beat map, or even just randomly while f2'ing in the song select about every 10 minutes. I have been bashing my head at this for a bit and have been able to play for an hour now without any crashes, and on-going. I will edit this if any crashes occur in the future.

### List of modifications
Mainly, the two changes I made which made the crashing stop was the following:
```bash
# 1. Installing winbind as it was an err from wine output
sudo apt update
sudo apt install winbind

# 2. Open winecfg from osu-wine
./osu-wine --winecfg
# Go to the Staging tab and uncheck "Enable CSMT for better graphic preformance"
```

Some other changes I made while debugging which may be related is the following:
- In osu!stable, change your "Release stream" in settings to "Cutting edge (Experimental)".
- In winecfg, change your Windows Version to Windows XP 64
- In the osu-wine script, comment out the following lines:
```bash
#export WINEESYNC=1 # Enables esync (when possible)
#export WINEFSYNC=1 # Enables fsync (when possible)
```

^ To be honest, I'm not quite sure what this does and if its good, but performance hasn't been impacted by commenting this out.

### Unrelated quality of life
This is unrelated but worth noting to anyone reading. While using a compositor such as picom/compton my latency is around 10ms, after killing the picom process my latency in osu! hovers around 0.9-1.5ms, this might be valuable to anyone who is experiencing high latency on Debian based distributions.

@LixxRarin @risexd1 @Jeydin21 
Are any of you able to confirm if this works on your end?

**Comment by Jeydin21** [comment] 2024-06-26 06:08
Sorry for the delayed response, I will try this when I wake up tomorrow 😄

**Comment by LixxRarin** [comment] 2024-06-26 19:39
> Olá agricultores, eu venho aqui com uma possível correção que funcionou na minha nova instalação do Debian usando i3wm.
> 
> Antes eu estava mostrando problemas semelhantes, o jogo congelava sempre que enviava pontuações, saía de um mapa de batidas ou até mesmo aleatoriamente enquanto f2'ing na música selecionava a cada 10 minutos. Eu venho batendo a cabeça nisso há um pouco e consegui jogar por uma hora agora sem nenhum acidente, e em andamento. Vou editar isso se algum travamento ocorrer no futuro.
> 
> ### Lista de modificações
> Principalmente, as duas mudanças que fiz que fizeram a parada de travamento foram as seguintes:
> 
> ```shell
> # 1. Installing winbind as it was an err from wine output
> sudo apt update
> sudo apt install winbind
> 
> # 2. Open winecfg from osu-wine
> ./osu-wine --winecfg
> # Go to the Staging tab and uncheck "Enable CSMT for better graphic preformance"
> ```
> 
> Algumas outras alterações que fiz durante a depuração que podem estar relacionadas é o seguinte:
> 
> * Em osu!stable, altere seu "Release stream" nas configurações para "Cutting edge (Experimental)".
> * No winecfg, altere sua versão do Windows para o Windows XP 64
> * No script osu-wine, comente as seguintes linhas:
> 
> ```shell
> #export WINEESYNC=1 # Enables esync (when possible)
> #export WINEFSYNC=1 # Enables fsync (when possible)
> ```
> 
> ^ Para ser honesto, não tenho certeza do que isso faz e se é bom, mas o desempenho não foi impactado por comentar isso.
> 
> ### Qualidade de vida não relacionada
> Isso não está relacionado, mas vale a pena notar para quem está lendo. Ao usar um compositor como picom/compton minha latência é de cerca de 10ms, depois de matar o processo picom minha latência em osu! paira em torno de 0.9-1.5ms, isso pode ser valioso para quem está experimentando alta latência em distribuições baseadas em Debian.
> 
> Algum de vocês é capaz de confirmar se isso funciona do seu lado?



> Hello farmers, I come here with a possible fix which worked on my fresh installation of Debian using i3wm.
> 
> Before I was showing similar issues, the game would freeze up whenever submitting scores, exiting a beat map, or even just randomly while f2'ing in the song select about every 10 minutes. I have been bashing my head at this for a bit and have been able to play for an hour now without any crashes, and on-going. I will edit this if any crashes occur in the future.
> 
> ### List of modifications
> Mainly, the two changes I made which made the crashing stop was the following:
> 
> ```shell
> # 1. Installing winbind as it was an err from wine output
> sudo apt update
> sudo apt install winbind
> 
> # 2. Open winecfg from osu-wine
> ./osu-wine --winecfg
> # Go to the Staging tab and uncheck "Enable CSMT for better graphic preformance"
> ```
> 
> Some other changes I made while debugging which may be related is the following:
> 
> * In osu!stable, change your "Release stream" in settings to "Cutting edge (Experimental)".
> * In winecfg, change your Windows Version to Windows XP 64
> * In the osu-wine script, comment out the following lines:
> 
> ```shell
> #export WINEESYNC=1 # Enables esync (when possible)
> #export WINEFSYNC=1 # Enables fsync (when possible)
> ```
> 
> ^ To be honest, I'm not quite sure what this does and if its good, but performance hasn't been impacted by commenting this out.
> 
> ### Unrelated quality of life
> This is unrelated but worth noting to anyone reading. While using a compositor such as picom/compton my latency is around 10ms, after killing the picom process my latency in osu! hovers around 0.9-1.5ms, this might be valuable to anyone who is experiencing high latency on Debian based distributions.
> 
> @LixxRarin @risexd1 @Jeydin21 Are any of you able to confirm if this works on your end?

I've switched to an arch linux-based distribution (which is working normally), but I'd like to test that out if I can :D

**Comment by LixxRarin** [comment] 2024-06-26 19:40
I've switched to an arch linux based-distribution (which is working normally), but I'd like to test that out if I can :D

**Comment by dceit** [comment] 2024-06-26 19:54
It was working perfectly fine for about 3 hours, then I decided to start streaming because I was feeling confident.
It ended up crashing within 5 minutes of starting the stream, very strange. I'm not quite sure anymore...

**Comment by NelloKudo** [comment] 2024-06-26 19:59
> It was working perfectly fine for about 3 hours, then I decided to start streaming because I was feeling confident. It ended up crashing within 5 minutes of starting the stream, very strange. I'm not quite sure anymore...
> 
> I also freeze / crash with the same error similar to:
> 
> ```
> 0398:err:sync:RtlpWaitForCriticalSection section 0035E308 (null) wait timed out in thread 0398, blocked by 0024, retrying (60 sec)
> ```
> 
> Though I would like to revive discussion / investigation into this if any of you have the free time. There is a plenty of Debian users who are using lazer right now because of this.

I’ll get a fresh install of Debian and try myself for a bit as well. Really strange issue as it only occurs on Debian/Ubuntu based distros ://

Unrelated but regarding your QoL advices above, yeah compositor turned off is a must on X11, but if you use Picom (which many do on i3) setting `unredir-if-possible=true;` in Picom’s config does the same job ;)

**Comment by dceit** [comment] 2024-06-29 04:22
> ~If you're having this issue and want to test a new winello release before it's finalized, here is a prerelease binary: https://github.com/whrvt/WineBuilder/releases/tag/9.11-2~
> 
> It's not guaranteed to fix the hanging/crashing issue, but it should generally be an improvement over the previous version. ~Until it's merged, you will have to copy the files from the archive to overwrite your old installation manually.~
> 
> Related PR: [NelloKudo/WineBuilder#2](https://github.com/NelloKudo/WineBuilder/pull/2)

I can confirm crash is still happening with this PR on Debian. Works out of the box on Arch based distros.

**Comment by NelloKudo** [comment] 2024-12-11 05:36
Closing this as it doesn't seem to be an issue anymore ever since the Proton release.

**Closed by NelloKudo** 2024-12-11 05:36 UTC
